CREATE TABLE `HOME_BUDGET`.`expense` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) NULL,
  `date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `description` VARCHAR(255) NULL,
  `amount` DECIMAL(9,2) NULL DEFAULT 0,
  PRIMARY KEY (`id`));

CREATE TABLE `HOME_BUDGET`.`income` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) NULL,
  `date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `description` VARCHAR(255) NULL,
  `amount` DECIMAL(9,2) NULL DEFAULT 0,
  PRIMARY KEY (`id`));